local_backend:
  url: http://localhost:8081/api/v1

backend:
  name: github
  repo: coderat-collective/zoff-website
  branch: main

media_folder: src/images
public_folder: ''

collections:
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - file: "src/pages/about.md"
        name: about
        label: About
        fields:
          - {label: "Languages", name: "languages", widget: "list", fields: [{label: "language", name: "language", widget: "string"}, {label: "Body", name: "body", widget: "markdown"}] }
      - file: "src/pages/metadata.md"
        name: metadata
        label: Metadata
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "siteURL", name: "siteurl", widget: "string"}

  - name: project_categories
    label: Project categories
    folder: "src/project_categories"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", value_type: "int", min: 1, step: 1, hint: "Place within the order of project categories"}
      - {label: "Projects", name: "projects", widget: "list", fields: [{label: "Caption", name: "caption", widget: "string"}, {label: "Project URL", name: "project_url", widget: "string", required: false}, {label: 'Image width [%]', name: 'scale', widget: 'number', value_type: 'int', min: 1, max: 100, step: 1}, {label: 'Is last project?', name: 'last_project', widget: 'boolean', hint: 'Image to be displayed at the end (e.g. as a funny joke or something...)?', default: true}, {label: "Image", name: "image", widget: "image"}] }
