name: Gatsby Publish Zoff Website

on:
  push:
    branches:
      - github_actions

jobs:
  # audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Audit npm pkts
  #       run: yarn audit
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # - name: Caching Gatsby
      #   id: gatsby-cache-build
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       public
      #       .cache
      #       node_modules
      #     key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
      #     restore-keys: |
      #       ${{ runner.os }}-gatsby-build-
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            public
            .cache
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
      # - name: Deploy
      #   run: yarn deploy
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: enriikke/gatsby-gh-pages-action@v2
  #       with:
  #         access-token: ${{ secrets.ACCESS_TOKEN }}
  #         deploy-branch: deploy
